#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Sep 14, 2019 03:36:44 PM PDT  platform: Windows NT


try:
    import Tkinter as tk
    from Tkinter import filedialog
except ImportError:
    import tkinter as tk
    from tkinter import filedialog

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
from PIL import Image, ImageTk    
import sys, os, csv, logging, fiona, json, utility
import xml.etree.ElementTree as ET, datetime
import HAST_PreProcess as hpp
from functools import reduce
#import HAST_GUI as hgui
#XML setup
tree = ET.parse('settings.xml')
base = tree.getroot()
"""
for node in tree.find('.//currentrun'):
    node.text = ''
    tree.write('settings.xml')
"""
#def readXMLNode(sNodeName,ET):
    

#Logging setup
LogFileName = tree.find('.//LogFileName').text
Level = tree.find('.//Level').text
#LogFileName = next(next(next(base.iter('data')).iter('Logging')).iter('LogFileName')).text
#Level = next(next(next(base.iter('data')).iter('Logging')).iter('Level')).text
if Level == 'INFO': logging.basicConfig(filename=LogFileName, filemode='w', level=logging.INFO)
else: logging.basicConfig(filename=LogFileName, filemode='w', level=logging.DEBUG)
logging.info(str(datetime.datetime.now()) +  ' Logging level set to: '+ str(Level))

#Field alias setup
defaultFields = {(item.tag if item.attrib['required'] != 'yes' else item.tag+'*'):item.text.split(',') for item in tree.find('.//PreProcessingFields')}
#defaultFields = {(item.tag if item.attrib['required'] != 'yes' else item.tag+'*'):item.text.split(',') for item in next(base.iter('fields'))}#{item.attributes['name'].value:item.firstChild.data.split(',') for item in items}

#Allowed file types setup
file_types = [('Type '+item,item) for item in tree.find('.//InputFileTypes').text.split(',')]
#file_types = [('Type '+item,item) for item in next(next(base.iter('GeneralSettings')).iter('InputFileTypes')).text.split(',')]

logging.debug(str(datetime.datetime.now()) +  ' Field Types: ' + str(file_types))


def set_Tk_var():
    global FileText
    FileText = tk.StringVar()

def checkform():# Check validity of form entries
    ents = fields
    root.preCheck = 0
    root.fields = {key:''for key, value in fields.items()}
    #root.fields = fields
    #print('fields ',[field.get() for field in fields.values()])
    #root.fields = {key:''for key, value in fields.items()}
    for key, field in ents.items():
        color = "yellow" if '*' not in key else "red"
        ent = field
        value = ent.get().upper()# if type(ent) != str else ent
        if '*' in key: root.valid[key] = False
        if len(root.csvFields) == 0:
            color = None# If no input file is selected there is no coloring.
        elif value != '':
            if value in root.csvFields:
                 root.fields[key] = value
                 color = "green"
                 if '*' in key: root.valid[key] = True
        else:
            for defaultField in list(map(lambda x: x.upper(), defaultFields[key])):
                 if defaultField in root.csvFields:
                      root.fields[key] = root.csvFields[root.csvFields.index(defaultField)]
                      color = "green"
                      if '*' in key: root.valid[key] = True
                      break
        ent.config(background=color)
        if key == 'TerrainID' or key == 'WBID':
            if color == 'green': root.preCheck += 1
    
    if False in root.valid.values(): w.Run.config(fg='grey',command='', state='disabled')
    else: w.Run.config(fg='black', command=analyze, state='normal')
    if root.preCheck == 2 and root.check:
        utility.popupmsg('Your input dataset has HU attributes assigned.\n Would you like to proceed to analysis?',startAnalysis)
    elif False in root.valid.values() and root.check:
        utility.popupmsg('The following required fields have not been found in your input file: \n ' + str(reduce(lambda x, y: x+y.strip('*')+', ' if root.valid[y] == False else x,root.valid,''))[:-2])
    root.check = False
    root.after(100, checkform)
    #root.after(100, checkform(button,fields))#Recheck fields every 0.1 second
    
def browse_button():
    root.valid = {}
    root.fields, root.csvFields = utility.browse(root.csvFields,root.fields,tree,'InputFileName',FileText,'InputPath',logging,fields,file_types)
    root.check = True

def analyze():
    logging.info(str(datetime.datetime.now()) +  ' Running analysis ')
    logging.info(str(datetime.datetime.now()) +  ' Input fields: ' + str(root.fields))
    #top_level.configure(cursor='hand2')
    for item in tree.find('.//PreProcessingFields'):
        item.attrib['inputFieldName'] = root.fields[item.tag] if item.attrib['required'] == 'no' else root.fields[item.tag+'*']
    tree.getroot().find('.//InputFileFieldMap').text = json.dumps(root.fields)
    #tree.getroot().find('.//InputFileName').text = filename
    tree.getroot().find('.//InputFileName').text = FileText.get()
    items = tree.find('.//PreProcessingFields')
    for key,value in root.fields.items():
        #print(key,value,items.find('.//'+key.strip('*')).text)
        if value not in items.find('.//'+key.strip('*')).text:
            items.find('.//'+key.strip('*')).text = items.find('.//'+key.strip('*')).text + ',' + value
    tree.write('settings.xml')
    hpp.HAST_dataPrep()
    #top_level.configure(cursor='')
    utility.popupmsg('Pre-Processing completed. Would you like to go to Analysis?', startAnalysis)

def MainScreen():
    utility.popupmsg('Are you sure you want to go to the main screen?', startMainScreen)

def startMainScreen():
    import HAST_Main_GUI_support
    destroy_window()
    HAST_Main_GUI_support.start_program()
    
def start_program():
    import HAST_PreProcess_GUI
    HAST_PreProcess_GUI.vp_start_gui()

def startAnalysis():
    import HAST_Analysis_GUI_support
    destroy_window()
    HAST_Analysis_GUI_support.start_program()
    
    
def Analysis():
    utility.popupmsg('Are you sure you want to go to Analysis?', startAnalysis)
   
    
def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    root.iconbitmap('../Images/Hu_Symbol.ico')
    root.csvFields = []# Input csv file fields
    global fields
    fields = {'Longitude*':w.LongitudeEntry,\
    'Latitude*':w.LatitudeEntry,\
    'SOID*':w.SOIDEntry,\
    'BuildingArea*':w.BuildingAreaEntry,\
    'BuildingValue*':w.BuildingValueEntry,\
    'ContentValue*':w.ContentValueEntry,\
    'HUSBT*':w.HUSBTEntry,\
    'CensusBlockID':w.CensusBlockIDEntry,\
    'TerrainID':w.TerrainIDEntry,\
    'WBID':w.WBIDEntry}
    
    root.fields = {key:''for key, value in fields.items()}
    root.valid = {}
    root.preCheck = 0
    root.check = False
    #top_level.configure(cursor='watch')
    # Gets the requested values of the height and widht.
    windowWidth = root.winfo_reqwidth()
    windowHeight = root.winfo_reqheight()
    print(windowWidth,windowHeight,root.winfo_screenwidth())
    # Gets both half the screen width/height and window width/height
    positionRight = int(root.winfo_screenwidth()/2 - windowWidth/2)
    positionDown = int(root.winfo_screenheight()/2 - windowHeight/2)
     
    # Positions the window in the center of the page.
    root.geometry("+{}+{}".format(positionRight, positionDown))
    
    
    root.after(100, checkform)
    photo_location = os.path.join(os.getcwd(),'..\images',"FileOpen_small.jpg")
    global _img0
    _img0 = ImageTk.PhotoImage(file=photo_location)
    w.SelectInput.configure(image=_img0)
    
    
def Exit():
    utility.popupmsg('Are you sure you want to quit?', destroy_window)

def destroy_window():
    # Function which closes the window.
    logging.info(str(datetime.datetime.now()) +  ' Window Closed')
    global top_level
    """
    for node in tree.find('.//currentrun'):
        node.text = ''
    tree.write('settings.xml')
    """
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import HAST_PreProcess_GUI
    HAST_PreProcess_GUI.vp_start_gui()



