#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Sep 30, 2019 05:38:55 PM PDT  platform: Windows NT

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from tkinter import *
import sys, webbrowser, os, utility
from tkinter import font, PhotoImage


import Python.HAST_Main_GUI as HMGUI
selectedButton = None
def set_Tk_var():
    global selectedButton
    selectedButton = tk.StringVar()
    selectedButton.set('2')

def destroy_window():
    print('HAST_Main_GUI_support.destroy_window')
    sys.stdout.flush()

def run():
    try: import HAST_PreProcess_GUI_support #as HPGS
    except: pass
    try: import HAST_Analysis_GUI_support #as HAGS
    except: pass
    try:
        # utility.popupmsg(HMGUI.selectedButton.get().text())
        if selectedButton.get()!= '':
            # utility.popupmsg('inside if')            
            destroy_window()
            import HAST_PreProcess_GUI_support
            import HAST_Analysis_GUI_support
            if selectedButton.get() == '2': HAST_PreProcess_GUI_support.start_program()
            elif selectedButton.get() == '1': HAST_Analysis_GUI_support.start_program()
            sys.stdout.flush()
    except:
        print("Unexpected error:", sys.exc_info()[0])
        # utility.popupmsg('ERROR')
        raise

w = None
root = None
def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

    # Modified due to relative path issues - UKS 03/24/2020
    # root.iconbitmap('../Images/Hu_Symbol.ico')
    root.iconbitmap(os.path.abspath('Images/Hu_Symbol.ico'))

    f = font.Font(w.SeeReadMe, w.SeeReadMe.cget("font"))
    f.configure(underline=True)
    w.SeeReadMe.configure(font=f)
    def callback(url):
        webbrowser.open_new(url)
    w.SeeReadMe.bind("<Button-1>", lambda e: callback(os.path.join(os.path.dirname(os.getcwd()),'help','readme.docx')))
    
    # Gets the requested values of the height and widht.
    windowWidth = root.winfo_reqwidth()
    windowHeight = root.winfo_reqheight()
    print(windowWidth,windowHeight)
    # Gets both half the screen width/height and window width/height
    positionRight = int(root.winfo_screenwidth()/2 - windowWidth)
    positionDown = int(root.winfo_screenheight()/2 - windowHeight)
     
    # Positions the window in the center of the page.
    root.geometry("+{}+{}".format(positionRight, positionDown))

top_level = None    
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
    
def start_program():
    # import Python.HAST_Main_GUI as HMGUI
    HMGUI.vp_start_gui()
    
if __name__ == '__main__':
    # import Python.HAST_Main_GUI as HMGUI
    HMGUI.vp_start_gui()





