#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Sep 25, 2019 08:58:11 PM PDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import select_window_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    select_window_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    select_window_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("447x332+898+322")
        top.title("Select")
        top.configure(background="#349ded")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.783, rely=0.873, height=33, width=88)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#0dc6ff")
        self.Button1.configure(command=select_window_support.pre_process)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Pre-Process''')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.022, rely=0.873, height=33, width=64)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#0dc6ff")
        self.Button2.configure(command=select_window_support.analyze)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Analyze''')

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.0, rely=0.0, relheight=0.858
                , relwidth=0.515)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(background="#349ded")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")

        self.Message1 = tk.Message(self.Labelframe1)
        self.Message1.place(relx=0.043, rely=0.035, relheight=0.912
                , relwidth=0.852, bordermode='ignore')
        self.Message1.configure(anchor='nw')
        self.Message1.configure(background="#349ded")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Your dataset must have the pre-requisite fields to be analyzed.

Required Fields:
-Longitude
-Latitude
-Specific Occupancy ID
-Building Area
-Building Value
-Hurricane Specific Building Type''')
        self.Message1.configure(width=196)

        self.Labelframe2 = tk.LabelFrame(top)
        self.Labelframe2.place(relx=0.515, rely=0.0, relheight=0.858
                , relwidth=0.47)
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(background="#349ded")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")

        self.Message2 = tk.Message(self.Labelframe2)
        self.Message2.place(relx=0.048, rely=0.035, relheight=0.947
                , relwidth=0.829, bordermode='ignore')
        self.Message2.configure(anchor='nw')
        self.Message2.configure(background="#349ded")
        self.Message2.configure(foreground="#000000")
        self.Message2.configure(highlightbackground="#d9d9d9")
        self.Message2.configure(highlightcolor="black")
        self.Message2.configure(text='''If your dataset is lacking these fields, you may pre-process it.''')
        self.Message2.configure(width=174)

if __name__ == '__main__':
    vp_start_gui()





