#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Sep 25, 2019 07:52:38 PM PDT  platform: Windows NT
#    Sep 25, 2019 07:54:18 PM PDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def analyze():
    import HUSAT_support
    destroy_window()
    HUSAT_support.start_program()
    print('select_window_support.analyze')
    sys.stdout.flush()

def pre_process():
    print('select_window_support.pre_process')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    root.iconbitmap('../Images/Hu_Symbol.ico')

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import select_window
    select_window.vp_start_gui()




